#!/bin/bash

# Script plots graphs for all *.dat files in the folder.
# It produces one *.pdf file for every input file.
# Usage: plot-all <work-dir>

curdir="$(dirname "$(readlink -f "$BASH_SOURCE[0]")")" > /dev/null

for f in $1/*.dat
do
    gnuplot -c "$curdir/plot.gp" "$f" "${f%.dat}.pdf"
done
